"""
deploy_dubbing_cloudflare.py
============================
Kaggle kernel script — runs on Kaggle's T4 GPU as a HEADLESS SCRIPT
(not an interactive notebook). Push with:

    kaggle kernels push -p . --accelerator NvidiaTeslaT4

Uses the ShadowGPU pattern:
  1. Install deps
  2. Write all pipeline files
  3. Patch IndicF5 model.py
  4. Launch Streamlit on port 8501
  5. Start Cloudflare Quick Tunnel
  6. Broadcast tunnel URL to ntfy.sh channel
  7. Stream ntfy.sh for SHUTDOWN_DUBBING signal (kill switch)

Environment variables read from Kaggle Secrets:
  - GEMINI_API_KEY : Google AI Studio key
  - HF_TOKEN       : HuggingFace read token (IndicF5 gated model)
  - NTFY_CHANNEL   : Your unique ntfy.sh channel name (set this below)

Local usage (after kernel is live):
  curl -s ntfy.sh/YOUR_NTFY_CHANNEL/raw   # Watch for the URL
  curl -d "SHUTDOWN_DUBBING" ntfy.sh/YOUR_NTFY_CHANNEL  # Kill it
"""

import os
import sys
import subprocess
import time
import re
import requests
import glob

# ── CONFIGURATION ────────────────────────────────────────────────────────────
# Set this to any unique random string. Use the same value in your local .env
NTFY_CHANNEL = "YOUR_NTFY_CHANNEL_HERE"   # <─── CHANGE THIS
# ─────────────────────────────────────────────────────────────────────────────


def send_log(message: str):
    """Broadcast a status message to your ntfy.sh channel."""
    try:
        requests.post(
            f"https://ntfy.sh/{NTFY_CHANNEL}",
            data=f"[DUBBING-GPU]: {message}".encode("utf-8"),
            timeout=10,
        )
    except Exception:
        pass
    print(f"[LOG] {message}", flush=True)


# ── Step 0: Read Kaggle Secrets ───────────────────────────────────────────────
send_log("Reading API keys from Kaggle Secrets...")
try:
    from kaggle_secrets import UserSecretsClient
    secrets = UserSecretsClient()
    GEMINI_API_KEY = secrets.get_secret("GEMINI_API_KEY")
    HF_TOKEN = secrets.get_secret("HF_TOKEN")
    os.environ["GEMINI_API_KEY"] = GEMINI_API_KEY
    os.environ["HF_TOKEN"] = HF_TOKEN
    send_log("Secrets loaded OK.")
except Exception as e:
    send_log(f"WARNING: Could not load secrets: {e}. Falling back to env vars.")
    GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
    HF_TOKEN = os.environ.get("HF_TOKEN", "")


# ── Step 1: Install system packages ──────────────────────────────────────────
send_log("Step 1/7: Installing system packages (ffmpeg, espeak-ng, fonts)...")
os.system("apt-get install -y -q ffmpeg rubberband-cli espeak-ng fonts-noto libsndfile1 2>&1")
send_log("Step 1/7 complete.")


# ── Step 2: Install Python packages ──────────────────────────────────────────
send_log("Step 2/7: Installing Python packages (this takes ~8 minutes)...")

pip_pkgs = [
    "soundfile", "pydub", "scipy", "resampy", "huggingface_hub",
    "safetensors", "faster-whisper", "demucs", "phonemizer",
    "indic-nlp-library", "sentence-transformers",
    "pyrubberband", "google-genai", "vocos", "streamlit", "requests",
]

for pkg in pip_pkgs:
    r = subprocess.run(
        [sys.executable, "-m", "pip", "install", "-q", pkg],
        capture_output=True, text=True
    )
    status = "OK" if r.returncode == 0 else "FAILED"
    print(f"  [{status}] {pkg}", flush=True)

# f5-tts must be before IndicF5
send_log("Installing f5-tts...")
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "f5-tts"],
               capture_output=True)

send_log("Installing IndicF5 from GitHub (largest step, ~3 min)...")
subprocess.run(
    [sys.executable, "-m", "pip", "install", "-q",
     "git+https://github.com/ai4bharat/IndicF5.git"],
    capture_output=True
)
send_log("Step 2/7 complete.")


# ── Step 3: Write all pipeline files ─────────────────────────────────────────
send_log("Step 3/7: Writing pipeline source files...")

WORK_DIR = "/kaggle/working"
os.makedirs(f"{WORK_DIR}/pipeline", exist_ok=True)
os.makedirs(f"{WORK_DIR}/utils", exist_ok=True)
os.makedirs(f"{WORK_DIR}/temp_processing", exist_ok=True)

for init in [f"{WORK_DIR}/pipeline/__init__.py", f"{WORK_DIR}/utils/__init__.py"]:
    open(init, "w").close()

# ── All pipeline file contents are defined as strings below ──────────────────
# (Generated by build_notebook.py on the local machine and pasted here)

PIPELINE_FILES = {}   # Will be populated below


# NOTE: pipeline/phoneme_counter.py is NO LONGER inlined here. The old copy was a
# syllable-counting heuristic that has since been replaced by the canonical
# espeak-ng real-phoneme counter. Both phoneme_counter.py and semantic_similarity.py
# are now written from the CANONICAL source by kaggle_generated_files.py (imported
# below), so there is a single source of truth and no drift. Regenerate that module
# with:  python kaggle/build_notebook.py

# ─── utils/audio_extraction.py ───────────────────────────────────────────────
PIPELINE_FILES["utils/audio_extraction.py"] = r'''
import os, subprocess

def extract_audio(video_path, output_audio_path):
    if not os.path.exists(video_path):
        raise FileNotFoundError(f"Video file not found: {video_path}")
    os.makedirs(os.path.dirname(output_audio_path) or ".", exist_ok=True)
    cmd = ["ffmpeg","-y","-i",video_path,"-vn","-acodec","pcm_s16le",
           "-ar","16000","-ac","1",output_audio_path]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"FFmpeg audio extraction failed:\n{r.stderr}")
    print(f"Audio extracted to: {output_audio_path}")
'''

# ─── utils/video_merge.py (Linux-adapted) ────────────────────────────────────
PIPELINE_FILES["utils/video_merge.py"] = r'''
import os, subprocess

def merge_video_audio_subs(video_path, audio_path, srt_path, output_path):
    cmd = ["ffmpeg","-y","-i",video_path,"-i",audio_path,
           "-vf","subtitles='" + srt_path + "':force_style='FontSize=18,"
           "PrimaryColour=&H00FFFFFF,OutlineColour=&H00000000,BorderStyle=1'",
           "-c:v","libx264","-c:a","aac",
           "-map","0:v:0","-map","1:a:0","-shortest",output_path]
    print(f"FFmpeg merge: {' '.join(cmd)}")
    try:
        subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=True)
        print("Video merging complete.")
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"FFmpeg failed:\n{e.stderr}")
    return output_path
'''

# Write all files defined above
for rel_path, content in PIPELINE_FILES.items():
    full_path = os.path.join(WORK_DIR, rel_path)
    with open(full_path, "w", encoding="utf-8") as f:
        f.write(content.lstrip("\n"))

send_log("Step 3/7 base files written. Now writing large pipeline files...")

# The large files (isochrony_translation, source_separation, voice_manager,
# duration_tts, transcription, audio_sync) are written by a sub-script
# that is generated locally via build_notebook.py.
# >>>  PASTE THE GENERATED CONTENT HERE  <<<
# (Run:  python kaggle/build_notebook.py  on your local machine,
#  then copy the GENERATED_LARGE_FILES block from kaggle/generated_files.py)

try:
    import kaggle_generated_files   # noqa
    send_log("Large pipeline files written from kaggle_generated_files module.")
except ImportError:
    send_log("WARNING: kaggle_generated_files not found — large files may be missing.")
    send_log("Run build_notebook.py locally and upload kaggle_generated_files.py as a dataset.")

send_log("Step 3/7 complete.")


# ── Step 4: Patch IndicF5 model.py ────────────────────────────────────────────
send_log("Step 4/7: Pre-downloading IndicF5 config + patching model.py...")

PATCHED_MODEL = r'''
import sys, os
from datetime import datetime

def debug_log(msg):
    t = datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
    print(f"[{t}] [HF_Model] {msg}", flush=True)

debug_log("model.py loaded (Kaggle-patched version).")
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(current_dir)

from transformers import PreTrainedModel, PretrainedConfig
import torch, numpy as np, soundfile as sf, io
from pydub import AudioSegment, silence
from huggingface_hub import hf_hub_download
from safetensors.torch import load_file
from f5_tts.infer.utils_infer import infer_process, load_model, load_vocoder, preprocess_ref_audio_text
from f5_tts.model import DiT

class INF5Config(PretrainedConfig):
    model_type = "inf5"
    def __init__(self, ckpt_path="checkpoints/model_best.pt",
                 vocab_path="checkpoints/vocab.txt",
                 speed=1.0, remove_sil=True, **kwargs):
        super().__init__(**kwargs)
        self.ckpt_path = ckpt_path
        self.vocab_path = vocab_path
        self.speed = speed
        self.remove_sil = remove_sil

class INF5Model(PreTrainedModel):
    config_class = INF5Config

    def load_state_dict(self, state_dict, strict=False):
        new_sd = {k.replace("._orig_mod.", "."): v for k, v in state_dict.items()}
        return super().load_state_dict(new_sd, strict=False)

    def __init__(self, config):
        debug_log("INF5Model.__init__ starting...")
        super().__init__(config)
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        debug_log(f"Device: {device}")

        # Step 1: Vocoder on CPU first (avoids meta-tensor OOM)
        debug_log("Loading vocoder on CPU...")
        vocoder = load_vocoder(vocoder_name="vocos", is_local=False, device=torch.device("cpu"))
        if str(device) != "cpu":
            vocoder = vocoder.to(device)
        self.__dict__["vocoder"] = vocoder
        debug_log("Vocoder loaded.")

        # Step 2: Vocab
        vocab_path = hf_hub_download(config.name_or_path, filename="checkpoints/vocab.txt")
        debug_log(f"Vocab: {vocab_path}")

        # Step 3: DiT architecture
        self.ema_model = load_model(
            DiT,
            dict(dim=1024, depth=22, heads=16, ff_mult=2, text_dim=512, conv_layers=4),
            mel_spec_type="vocos", vocab_file=vocab_path, device=device
        )
        debug_log("DiT architecture loaded.")

        # Step 3b: Real weights from model.safetensors
        ckpt_path = hf_hub_download(config.name_or_path, filename="model.safetensors")
        state_dict = load_file(ckpt_path, device=str(device))
        ema_state = {}
        for k, v in state_dict.items():
            if k.startswith("ema_model."):
                nk = k[len("ema_model."):]
                if nk.startswith("_orig_mod."):
                    nk = nk[len("_orig_mod."):]
                nk = nk.replace("._orig_mod.", ".")
                ema_state[nk] = v
        missing, unexpected = self.ema_model.load_state_dict(ema_state, strict=False)
        debug_log(f"Weights loaded. missing={len(missing)}, unexpected={len(unexpected)}")
        debug_log("INF5Model.__init__ complete!")

    def forward(self, text, ref_audio_path, ref_text):
        if not os.path.exists(ref_audio_path):
            raise FileNotFoundError(f"Ref audio not found: {ref_audio_path}")
        ref_audio, ref_text = preprocess_ref_audio_text(ref_audio_path, ref_text)
        self.ema_model.to(self.device)
        self.vocoder.to(self.device)
        audio, sr, _ = infer_process(
            ref_audio, ref_text, text,
            self.ema_model, self.vocoder,
            mel_spec_type="vocos", speed=self.config.speed, device=self.device,
        )
        buf = io.BytesIO()
        sf.write(buf, audio, samplerate=24000, format="WAV")
        buf.seek(0)
        seg = AudioSegment.from_file(buf, format="wav")
        if self.config.remove_sil:
            parts = silence.split_on_silence(seg, min_silence_len=1000, silence_thresh=-50, keep_silence=500)
            seg = sum(parts, AudioSegment.silent(duration=0))
        seg = seg.apply_gain(-20.0 - seg.dBFS)
        return np.array(seg.get_array_of_samples())
'''

try:
    from transformers import AutoConfig
    AutoConfig.from_pretrained("ai4bharat/IndicF5", trust_remote_code=True, token=HF_TOKEN)
except Exception as e:
    send_log(f"Config cache attempt: {e}")

patterns = glob.glob(os.path.expanduser(
    "~/.cache/huggingface/modules/transformers_modules/ai4bharat/IndicF5/*/model.py"
))

if patterns:
    model_py_path = patterns[0]
    with open(model_py_path, "w", encoding="utf-8") as f:
        f.write(PATCHED_MODEL.lstrip("\n"))
    send_log(f"model.py patched at: {model_py_path}")
else:
    # Save for later patching when model is first loaded
    with open(f"{WORK_DIR}/pipeline/indicf5_model_patched.py", "w", encoding="utf-8") as f:
        f.write(PATCHED_MODEL.lstrip("\n"))
    send_log("model.py saved for deferred patching (will be applied on first load)")

send_log("Step 4/7 complete.")


# ── Step 5: Install cloudflared ────────────────────────────────────────────────
send_log("Step 5/7: Installing cloudflared tunnel binary...")
os.system("wget -q -O /usr/local/bin/cloudflared "
          "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64")
os.system("chmod +x /usr/local/bin/cloudflared")
ver = subprocess.check_output(["/usr/local/bin/cloudflared", "--version"]).decode().strip()
send_log(f"cloudflared installed: {ver}")
send_log("Step 5/7 complete.")


# ── Step 6: Launch Streamlit ──────────────────────────────────────────────────
send_log("Step 6/7: Starting Streamlit app on port 8501...")

env = os.environ.copy()
env.update({
    "GEMINI_API_KEY": GEMINI_API_KEY,
    "HF_TOKEN": HF_TOKEN,
    "PYTHONIOENCODING": "utf-8",
})

streamlit_proc = subprocess.Popen(
    [sys.executable, "-m", "streamlit", "run", f"{WORK_DIR}/app.py",
     "--server.port", "8501",
     "--server.headless", "true",
     "--browser.gatherUsageStats", "false",
     "--server.maxUploadSize", "500"],
    env=env,
    cwd=WORK_DIR,
)

time.sleep(8)
if streamlit_proc.poll() is not None:
    send_log("ERROR: Streamlit exited unexpectedly!")
else:
    send_log(f"Streamlit running (PID: {streamlit_proc.pid})")

send_log("Step 6/7 complete.")


# ── Step 7: Cloudflare Quick Tunnel ──────────────────────────────────────────
send_log("Step 7/7: Opening Cloudflare Quick Tunnel...")

tunnel_proc = subprocess.Popen(
    ["/usr/local/bin/cloudflared", "tunnel", "--url", "http://localhost:8501"],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True,
)

public_url = ""
for line in tunnel_proc.stdout:
    print(f"  [cloudflared] {line.rstrip()}", flush=True)
    match = re.search(r"https://[a-zA-Z0-9\-]+\.trycloudflare\.com", line)
    if match:
        public_url = match.group(0)
        break

if public_url:
    msg = f"DUBBING APP IS LIVE! Open: {public_url}"
    requests.post(
        f"https://ntfy.sh/{NTFY_CHANNEL}",
        data=msg.encode("utf-8"),
        timeout=10,
    )
    send_log(msg)
else:
    send_log("ERROR: Could not extract Cloudflare URL from tunnel output.")

send_log("All steps complete. Listening for SHUTDOWN_DUBBING signal...")

# ── Kill Switch ───────────────────────────────────────────────────────────────
try:
    response = requests.get(f"https://ntfy.sh/{NTFY_CHANNEL}/raw", stream=True, timeout=None)
    for line in response.iter_lines():
        if line:
            decoded = line.decode("utf-8")
            if "SHUTDOWN_DUBBING" in decoded:
                requests.post(
                    f"https://ntfy.sh/{NTFY_CHANNEL}",
                    data="[DUBBING-GPU]: Kill switch activated! Shutting down.".encode("utf-8"),
                    timeout=10,
                )
                tunnel_proc.terminate()
                streamlit_proc.terminate()
                os._exit(0)
except Exception:
    pass
